### ISSUE TITLE
GitHub不是云盘！

### ISSUE THREAD

**Issue by prprnya** [ToKiNoBug/3dPixelPaintingInMinecraft#1]
> 不要简单地将 **GitHub** 看作储存文件的云盘！

在仓库中仅保留源代码，并将所有编译产生的、需要发布的二进制文件打包上传到 [**Releases页面**](https://github.com/ToKiNoBug/3dPixelPaintingInMinecraft/releases) 以保持仓库整洁  
善用 **Git** 的版本控制功能（比如为特定提交打上**标签**），不要将源码按版本分设目录

若对具体细节有任何疑问，可参考 [**Git官方文档**](https://git-scm.com/book/zh/v2) 和 [**GitHub官方文档**](https://docs.github.com/cn/github)

**Comment by CberYellowstone** [comment]
同意，希望整理仓库内容，善用github

**Comment by ToKiNoBug** [comment]
刚刚整理了一下这个仓库，应该……没问题了吧……
